# Generated by Django 4.2.13 on 2024-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="original_images/")),
                (
                    "preprocessed_image",
                    models.ImageField(blank=True, upload_to="preprocessed_images/"),
                ),
                (
                    "encrypted_image",
                    models.ImageField(blank=True, upload_to="encrypted_images/"),
                ),
            ],
        ),
    ]
