# Generated by Django 4.2.15 on 2024-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptDecrypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='complex_matrix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='encrypted_image',
            field=models.ImageField(blank=True, null=True, upload_to='encrypted_images/'),
        ),
    ]
