# Generated by Django 4.2.15 on 2024-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptDecrypt', '0003_send_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='generated_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='encrypted_image',
            field=models.ImageField(blank=True, upload_to='encrypted_images/'),
        ),
    ]
