# Generated by Django 4.2.15 on 2024-10-17 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EncryptDecrypt', '0006_receive_decrypted_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
